services:
  - type: web
    name: aichatbot
    env: python
    plan: free
    buildCommand: |
      echo "python-3.11.9" > runtime.txt
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.address=0.0.0.0 --server.port=10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PORT
        value: 10000
